### ISSUE TITLE
Warenkorb Austausch geht nicht mehr

### ISSUE THREAD

**Issue by sedrubal** [FAU-Inf2/fablab-server#1]
Der Warenkorb Import für unsere Kasse scheint weder mit dem Simulator, noch mit der echten Kasse zu funktionieren. Das ist nicht gut, da dann die frisch releaste App fast keinen Sinn für die Besucher hat. Der passende Issue von unserer Kasse ist hier: https://github.com/fau-fablab/FabLabKasse/issues/17

**Comment by 0xhansdampf** [comment]
Ihr testet mit der Release-App gegen den Developement-Server, das kann natürlich nicht gut gehen.
Das ist der Production-Server ec2-52-28-173-123.eu-central-1.compute.amazonaws.com

**Comment by sedrubal** [comment]
danke
